// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaSaludGoya.Data;

#nullable disable

namespace SistemaSaludGoya.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260609135708_InitialSupabase")]
    partial class InitialSupabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaSaludGoya.Models.Consulta", b =>
                {
                    b.Property<int>("IdConsulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdConsulta"));

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("FechaConsulta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdTurno")
                        .HasColumnType("integer");

                    b.Property<string>("Indicaciones")
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.HasKey("IdConsulta");

                    b.HasIndex("IdTurno")
                        .IsUnique();

                    b.ToTable("consulta", (string)null);
                });

            modelBuilder.Entity("SistemaSaludGoya.Models.Documento", b =>
                {
                    b.Property<int>("IdDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDocumento"));

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdConsulta")
                        .HasColumnType("integer");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdDocumento");

                    b.HasIndex("IdConsulta");

                    b.ToTable("documento", (string)null);
                });

            modelBuilder.Entity("SistemaSaludGoya.Models.Especialidad", b =>
                {
                    b.Property<int>("IdEspecialidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEspecialidad"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdEspecialidad");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("especialidad", (string)null);
                });

            modelBuilder.Entity("SistemaSaludGoya.Models.Estudio", b =>
                {
                    b.Property<int>("IdEstudio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstudio"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<int>("IdConsulta")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdEstudio");

                    b.HasIndex("IdConsulta");

                    b.ToTable("estudio", (string)null);
                });

            modelBuilder.Entity("SistemaSaludGoya.Models.HistorialMedico", b =>
                {
                    b.Property<int>("IdHistorialMedico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdHistorialMedico"));

                    b.Property<int>("IdPaciente")
                        .HasColumnType("integer");

                    b.HasKey("IdHistorialMedico");

                    b.HasIndex("IdPaciente")
                        .IsUnique();

                    b.ToTable("historial_medico", (string)null);
                });

            modelBuilder.Entity("SistemaSaludGoya.Models.HorarioAtencion", b =>
                {
                    b.Property<int>("IdHorarioAtencion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdHorarioAtencion"));

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("HoraDesde")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraHasta")
                        .HasColumnType("interval");

                    b.Property<int>("IdMedico")
                        .HasColumnType("integer");

                    b.HasKey("IdHorarioAtencion");

                    b.HasIndex("IdMedico");

                    b.ToTable("horario_atencion", (string)null);
                });

            modelBuilder.Entity("SistemaSaludGoya.Models.Medico", b =>
                {
                    b.Property<int>("IdMedico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMedico"));

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("IdMedico");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.HasIndex("Matricula")
                        .IsUnique();

                    b.ToTable("medico", (string)null);
                });

            modelBuilder.Entity("SistemaSaludGoya.Models.MedicoEspecialidad", b =>
                {
                    b.Property<int>("IdMedico")
                        .HasColumnType("integer");

                    b.Property<int>("IdEspecialidad")
                        .HasColumnType("integer");

                    b.HasKey("IdMedico", "IdEspecialidad");

                    b.HasIndex("IdEspecialidad");

                    b.ToTable("medico_especialidad", (string)null);
                });

            modelBuilder.Entity("SistemaSaludGoya.Models.Paciente", b =>
                {
                    b.Property<int>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPaciente"));

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<DateTime?>("FechaFinSuspension")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoSuspension")
                        .HasColumnType("text");

                    b.Property<bool>("Suspendido")
                        .HasColumnType("boolean");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("IdPaciente");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("paciente", (string)null);
                });

            modelBuilder.Entity("SistemaSaludGoya.Models.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPago"));

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdTurno")
                        .HasColumnType("integer");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Pagado")
                        .HasColumnType("boolean");

                    b.HasKey("IdPago");

                    b.HasIndex("IdTurno")
                        .IsUnique();

                    b.ToTable("pago", (string)null);
                });

            modelBuilder.Entity("SistemaSaludGoya.Models.Permiso", b =>
                {
                    b.Property<int>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPermiso"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdPermiso");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("permiso", (string)null);
                });

            modelBuilder.Entity("SistemaSaludGoya.Models.Receta", b =>
                {
                    b.Property<int>("IdReceta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdReceta"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdConsulta")
                        .HasColumnType("integer");

                    b.HasKey("IdReceta");

                    b.HasIndex("IdConsulta");

                    b.ToTable("receta", (string)null);
                });

            modelBuilder.Entity("SistemaSaludGoya.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdRol");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("rol", (string)null);
                });

            modelBuilder.Entity("SistemaSaludGoya.Models.RolPermiso", b =>
                {
                    b.Property<int>("IdRol")
                        .HasColumnType("integer");

                    b.Property<int>("IdPermiso")
                        .HasColumnType("integer");

                    b.HasKey("IdRol", "IdPermiso");

                    b.HasIndex("IdPermiso");

                    b.ToTable("rol_permiso", (string)null);
                });

            modelBuilder.Entity("SistemaSaludGoya.Models.Turno", b =>
                {
                    b.Property<int>("IdTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTurno"));

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdMedico")
                        .HasColumnType("integer");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoConsulta")
                        .HasColumnType("text");

                    b.HasKey("IdTurno");

                    b.HasIndex("IdMedico");

                    b.HasIndex("IdPaciente");

                    b.ToTable("turno", (string)null);
                });

            modelBuilder.Entity("SistemaSaludGoya.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("SistemaSaludGoya.Models.UsuarioRol", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer");

                    b.HasKey("IdUsuario", "IdRol");

                    b.HasIndex("IdRol");

                    b.ToTable("usuario_rol", (string)null);
                });

            modelBuilder.Entity("SistemaSaludGoya.Models.Consulta", b =>
                {
                    b.HasOne("SistemaSaludGoya.Models.Turno", "Turno")
                        .WithOne("Consulta")
                        .HasForeignKey("SistemaSaludGoya.Models.Consulta", "IdTurno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("SistemaSaludGoya.Models.Documento", b =>
                {
                    b.HasOne("SistemaSaludGoya.Models.Consulta", "Consulta")
                        .WithMany("Documentos")
                        .HasForeignKey("IdConsulta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("SistemaSaludGoya.Models.Estudio", b =>
                {
                    b.HasOne("SistemaSaludGoya.Models.Consulta", "Consulta")
                        .WithMany("Estudios")
                        .HasForeignKey("IdConsulta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("SistemaSaludGoya.Models.HistorialMedico", b =>
                {
                    b.HasOne("SistemaSaludGoya.Models.Paciente", "Paciente")
                        .WithOne("HistorialMedico")
                        .HasForeignKey("SistemaSaludGoya.Models.HistorialMedico", "IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("SistemaSaludGoya.Models.HorarioAtencion", b =>
                {
                    b.HasOne("SistemaSaludGoya.Models.Medico", "Medico")
                        .WithMany("Horarios")
                        .HasForeignKey("IdMedico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("SistemaSaludGoya.Models.Medico", b =>
                {
                    b.HasOne("SistemaSaludGoya.Models.Usuario", "Usuario")
                        .WithOne("Medico")
                        .HasForeignKey("SistemaSaludGoya.Models.Medico", "IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaSaludGoya.Models.MedicoEspecialidad", b =>
                {
                    b.HasOne("SistemaSaludGoya.Models.Especialidad", "Especialidad")
                        .WithMany("Medicos")
                        .HasForeignKey("IdEspecialidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaSaludGoya.Models.Medico", "Medico")
                        .WithMany("Especialidades")
                        .HasForeignKey("IdMedico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidad");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("SistemaSaludGoya.Models.Paciente", b =>
                {
                    b.HasOne("SistemaSaludGoya.Models.Usuario", "Usuario")
                        .WithOne("Paciente")
                        .HasForeignKey("SistemaSaludGoya.Models.Paciente", "IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaSaludGoya.Models.Pago", b =>
                {
                    b.HasOne("SistemaSaludGoya.Models.Turno", "Turno")
                        .WithOne("Pago")
                        .HasForeignKey("SistemaSaludGoya.Models.Pago", "IdTurno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("SistemaSaludGoya.Models.Receta", b =>
                {
                    b.HasOne("SistemaSaludGoya.Models.Consulta", "Consulta")
                        .WithMany("Recetas")
                        .HasForeignKey("IdConsulta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("SistemaSaludGoya.Models.RolPermiso", b =>
                {
                    b.HasOne("SistemaSaludGoya.Models.Permiso", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("IdPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaSaludGoya.Models.Rol", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SistemaSaludGoya.Models.Turno", b =>
                {
                    b.HasOne("SistemaSaludGoya.Models.Medico", "Medico")
                        .WithMany("Turnos")
                        .HasForeignKey("IdMedico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaSaludGoya.Models.Paciente", "Paciente")
                        .WithMany("Turnos")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("SistemaSaludGoya.Models.UsuarioRol", b =>
                {
                    b.HasOne("SistemaSaludGoya.Models.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaSaludGoya.Models.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaSaludGoya.Models.Consulta", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("Estudios");

                    b.Navigation("Recetas");
                });

            modelBuilder.Entity("SistemaSaludGoya.Models.Especialidad", b =>
                {
                    b.Navigation("Medicos");
                });

            modelBuilder.Entity("SistemaSaludGoya.Models.Medico", b =>
                {
                    b.Navigation("Especialidades");

                    b.Navigation("Horarios");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("SistemaSaludGoya.Models.Paciente", b =>
                {
                    b.Navigation("HistorialMedico")
                        .IsRequired();

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("SistemaSaludGoya.Models.Permiso", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("SistemaSaludGoya.Models.Rol", b =>
                {
                    b.Navigation("RolPermisos");

                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("SistemaSaludGoya.Models.Turno", b =>
                {
                    b.Navigation("Consulta");

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("SistemaSaludGoya.Models.Usuario", b =>
                {
                    b.Navigation("Medico");

                    b.Navigation("Paciente");

                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
